// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.Constants;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

/**
 *
 */
public class Hopper extends Subsystem {

    private WPI_VictorSPX hopperVictorTop;
    private WPI_VictorSPX hopperVictorBottom;

    public Hopper() {
        hopperVictorTop = new WPI_VictorSPX(Constants.HopperConstants.VICTOR_CAN_TOP);
        hopperVictorBottom = new WPI_VictorSPX(Constants.HopperConstants.VICTOR_CAN_BOTTOM);
        // hopperVictorFollower.follow(hopperVictor);
    }

    /**
     * @return the hopperVictorTop
     */
    public WPI_VictorSPX getHopperVictorTop() {
        return hopperVictorTop;
    }

    /**
     * @return the hopperVictorBottom
     */
    public WPI_VictorSPX getHopperVictorBottom() {
        return hopperVictorBottom;
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new HopperHold());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
