// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.Solenoid;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Spitter extends SubsystemBase {

    private Solenoid solenoidTrapDoor;
    private WPI_VictorSPX spitterVictor;

    public Spitter() {
        solenoidTrapDoor = new Solenoid(Constants.SpitterConstants.SOLENOID_CAN, 1);
        addChild("solenoidTrapDoor", solenoidTrapDoor);
        spitterVictor = new WPI_VictorSPX(Constants.SpitterConstants.VICTOR_CAN);
    }

    public Solenoid getTrapDoor() {
        return solenoidTrapDoor;
    }

    public WPI_VictorSPX getVictor() {
        return spitterVictor;
    }

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
